### PR TITLE
feat(apply): wait until deployment dependencies have succeeded

### PR DESCRIPTION
**Pull request by pallabpain**
### Description
This commit introduces a flag to wait until deployment dependencies are in a running state. The existing code proceeds once dependencies are in provisioning phase.

### CODE REVIEW

**Comment by pallabpain** [comment]
@amitsingh21 I have implemented this in the v2 PR. We can close this once it is merged. The usage will be something like this.
```
depends:
- kind: deployment
  nameOrGUID: wms-server
  wait: true
```

**Comment by pallabpain** [comment]
Closing this in favour of the manifest based approach introduced in v2.

**Comment by rrkumarshikhar** [comment]
Reopening this PR for updating the app-image to 8.1 for v1 deployments. This PR will be closed after the v2-migration is completed.

**Comment by pallabpain** [comment]
Not relevant anymore. Hence closing the PR.

**Pull request closed without merging**
